In [1]:
import torch
import numpy as np

In [3]:
input_size = 4
hidden_size = 2

In [5]:
# 1-hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]
input_data_np = np.array([[h, e, l, l, o],
                        [e, o, l, l, l],
                        [l, l, e, e, l]], dtype=np.float32)

In [6]:
input_data_np.shape

(3, 5, 4)

In [7]:
input_data_np

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)

In [8]:
# transfrom as torch tensor
input_data = torch.Tensor(input_data_np)

In [9]:
input_data.shape

torch.Size([3, 5, 4])

In [10]:
# 실질적인 RNN 코드
rnn = torch.nn.RNN(input_size, hidden_size)
outputs, _status = rnn(input_data)

In [11]:
rnn

RNN(4, 2)

In [14]:
outputs

tensor([[[ 0.9525, -0.5397],
         [ 0.8024, -0.8754],
         [ 0.8991, -0.4510],
         [ 0.8991, -0.4510],
         [ 0.9249, -0.6854]],

        [[ 0.2148, -0.6238],
         [ 0.5931, -0.3071],
         [ 0.5760,  0.1037],
         [ 0.5760,  0.1037],
         [ 0.4871,  0.1183]],

        [[ 0.7773, -0.3364],
         [ 0.7297, -0.0965],
         [ 0.6439, -0.7504],
         [ 0.6439, -0.7504],
         [ 0.8316, -0.1613]]], grad_fn=<StackBackward>)

In [15]:
outputs.shape

torch.Size([3, 5, 2])

In [16]:
_status

tensor([[[ 0.7773, -0.3364],
         [ 0.7297, -0.0965],
         [ 0.6439, -0.7504],
         [ 0.6439, -0.7504],
         [ 0.8316, -0.1613]]], grad_fn=<StackBackward>)

In [17]:
_status.shape

torch.Size([1, 5, 2])