In [29]:
import torch

In [30]:
char_set = ['h', 'i', 'e', 'l', 'o']

In [31]:
# hyper parameters
input_size = len(char_set)
hidden_size = len(char_set)
learning_rate = 0.1

In [32]:
# data setting
x_data = [[0, 1, 0, 2, 3, 3]] # hihell
x_one_hot = [[[1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [1, 0, 0, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 1, 0]]]
y_data = [[1, 0, 2, 3, 3, 4]] # ihello

In [33]:
x_one_hot

[[[1, 0, 0, 0, 0],
  [0, 1, 0, 0, 0],
  [1, 0, 0, 0, 0],
  [0, 0, 1, 0, 0],
  [0, 0, 0, 1, 0],
  [0, 0, 0, 1, 0]]]

In [34]:
# transform as torch tnesor variable
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

In [35]:
X

tensor([[[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.]]])

In [36]:
X.shape

torch.Size([1, 6, 5])

In [37]:
Y

tensor([[1, 0, 2, 3, 3, 4]])

In [38]:
Y.shape

torch.Size([1, 6])

In [39]:
sample = "if you want you"

In [40]:
# make dictionary
char_set = list(set(sample))
char_dic = {c: i for i, c in enumerate(char_set)}

In [41]:
char_set

['t', 'f', 'w', 'y', 'u', 'n', 'i', 'o', ' ', 'a']

In [42]:
char_dic

{'t': 0,
 'f': 1,
 'w': 2,
 'y': 3,
 'u': 4,
 'n': 5,
 'i': 6,
 'o': 7,
 ' ': 8,
 'a': 9}

In [54]:
# hyper parameters
input_size = len(char_dic)
hidden_size = len(char_dic)
learning_rate = 0.1

In [55]:
# data setting
sample_idx = [char_dic[c] for c in sample]
x_data = [sample_idx[:-1]] # if you want yo
# x_data = [[0, 1, 0, 2, 3, 3]] # hihell
x_one_hot = [np.eye(dic_size)[x] for x in x_data]
# #x_one_hot = [[[1, 0, 0, 0, 0],
#               [0, 1, 0, 0, 0],
#               [1, 0, 0, 0, 0],
#               [0, 0, 1, 0, 0],
#               [0, 0, 0, 1, 0],
#               [0, 0, 0, 1, 0]]]
y_data = [sample_idx[1:]] # if you want you           
#y_data = [[1, 0, 2, 3, 3, 4]] # ihello

In [56]:
x_data

[[6, 1, 8, 3, 7, 4, 8, 2, 9, 5, 0, 8, 3, 7]]

In [57]:
x_one_hot

[array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])]

In [58]:
y_data

[[1, 8, 3, 7, 4, 8, 2, 9, 5, 0, 8, 3, 7, 4]]

In [59]:
# transform as torch tnesor variable
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

In [60]:
X

tensor([[[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]])

In [61]:
X.shape

torch.Size([1, 14, 10])

In [62]:
Y

tensor([[1, 8, 3, 7, 4, 8, 2, 9, 5, 0, 8, 3, 7, 4]])

In [63]:
Y.shape

torch.Size([1, 14])

In [64]:
# declare RNN
rnn = torch.nn.RNN(input_size, hidden_size, batch_first=True) #batch_first guarantees the order of output=(B,S,F)

In [66]:
# loss & optimizer setting
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(rnn.parameters(), learning_rate)